### ISSUE TITLE
first dice in success roll is always at max

### ISSUE THREAD

**Issue by Yijare** [Gawdl3y/discord-rpbot#13]
Hey there. Everytime we roll an success roll the first dice has always the maximum.

!roll 6 > 5 - we always roll a 6
!roll 6d6 > 30, the first dice is always at 6
!roll 666 > x, where x is 1 - 665, the dice is always a 666

**Comment by Gawdl3y** [comment]
The first and last examples are because you're using a static number, not a dice expression. The second one is just false. Here's my very first attempt: 
![image](https://user-images.githubusercontent.com/279900/39409418-ade3839c-4bb4-11e8-9218-f5f396a16020.png)
