### ISSUE TITLE
Bug, always crit

### ISSUE THREAD

**Issue by SenseiSabbia** [Gawdl3y/discord-rpbot#18]
if i write " !rolld 20+15 " the die will always be 20, at least in my server

tested a lot of times

![image](https://user-images.githubusercontent.com/48697027/54564948-61d54180-49cd-11e9-958c-3b792c371b43.png)

**Comment by Gawdl3y** [comment]
That's not rolling a d20 and adding 15, that's just doing 20 (raw number) + 15. Do `!roll d20 + 15`.

**Comment by SenseiSabbia** [comment]
Yeah, but it only works with 20, try, like !rolld 37+4 or !roll 92+13

Il ven 29 mar 2019, 20:53 Schuyler Cebulskie <notifications@github.com> ha
scritto:

**Comment by Gawdl3y** [comment]
![image](https://user-images.githubusercontent.com/279900/55259608-8981a080-523c-11e9-95ca-cfc74433b2b9.png)
