### ISSUE TITLE
Advanced expressions randomize incorrectly 

### ISSUE THREAD

**Issue by Arkanoid0** [Gawdl3y/discord-rpbot#4]
Currently, !roll 100 is the same as !roll d100 or !roll 1d100, but !roll 100+1 always gives 101, instead of rolling 100 and adding, unlike !roll 1d100+1

**Comment by Gawdl3y** [comment]
`!roll 100` is a special-case format that gets interpreted as `!roll d100`. It will not be possible to omit the `d` for anything other than a single plain number, as anything else is considered a full dice expression. You will need to do `!roll d100 + 1`.

**Comment by Arkanoid0** [comment]
That's exactly my point it should be considered an invalid expression but currently it just does the math instead of throwing an error, allowing for the possibility of cheating if you are crafty. Desired behavior is either to throw an error or work exactly the same way as with the data identifier.

This is a very easy mistake to make accidentally, my group did it 3 times in one roll before we figured out that it's a bug.

**Comment by Gawdl3y** [comment]
It's behaving exactly as intended, and is definitely not a bug. There's no way to distinguish whether you would want `d100 + 1`, `d100 + d1`, `100 + d1`, or `100 + 1`. In this case, there is one obviously correct choice, but that won't always be the case. What about `5 + 4`, for example?

**Comment by Arkanoid0** [comment]
Yeah, that's kind of my point, no matter which of those expressions you intended, nobody is expecting it to add the numbers together when you are invoking a !roll command. There is no correct interpretation here, so the sensible thing is to instead refuse to do anything.
