### ISSUE TITLE
Max and Min Roll

### ISSUE THREAD

**Issue by RelaxedBell** [Gawdl3y/discord-rpbot#8]
Both are not working.

**Comment by Gawdl3y** [comment]
Both are not supported.

**Comment by Gawdl3y** [comment]
Misinterpreted what you said - you probably mean the min/max roll commands. Both are working fine. 
![image](https://user-images.githubusercontent.com/279900/35867136-0c52dfd2-0b27-11e8-9cc5-555f1c1574e0.png)
